name       : kjobwidgets
version    : 5.96.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kjobwidgets-5.96.0.tar.xz : b4090c614f64ef7567c560c402ad05c81d4c5ba10c9522021247064ced4e30f0
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kcoreaddons-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
