name       : kjobwidgets
version    : 5.48.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kjobwidgets-5.48.0.tar.xz : dcf8d2c3049bfda5224d46d2caeef4da2f5f62d2c7c5524926b31a35d7e5aa28
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
