name       : kjobwidgets
version    : 5.32.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.32/kjobwidgets-5.32.0.tar.xz : 04254403cf3de9458466e12283a0fc60c156c3be92848e1e5032462a5e1d1b52
license    : LGPL-2.1
component  : desktop.library
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
