name       : kjobwidgets
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/kjobwidgets-5.35.0.tar.xz : 7437aca391723314b44f951ee1dde74b309c5d04c8f25b4f86c8a9e45f720c64
license    : LGPL-2.1
component  : desktop.library
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
