name       : kjobwidgets
version    : 5.41.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kjobwidgets-5.41.0.tar.xz : 1b97f3f89987d9dd58909ff1e1ef4fa81ffb144bb589cf80c5deae8ca8996db9
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
