name       : kjobwidgets
version    : 5.76.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kjobwidgets-5.76.0.tar.xz : 850b6af6c027476e594e6ed77ea0e531abb69ff726fce41b91e541fbee3ecedf
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
