name       : kjobwidgets
version    : 5.91.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/kjobwidgets-5.91.0.tar.xz : 5b909845e5707689e010d636cd36fb9b3b11fdddd37561b27d71a2234df3f392
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kcoreaddons-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
