name       : kjobwidgets
version    : 5.83.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kjobwidgets-5.83.0.tar.xz : f3b9371a77ee245a60ea808f2e6928575187ac06b34818b76f1c147dfb95b5e7
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kcoreaddons-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
