name       : kjobwidgets
version    : 5.67.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kjobwidgets-5.67.0.tar.xz : c74d291dfeb5b4e1a0002e76a2761bfdc379354ccd1937670c77418c06906e7f
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
