name       : kjobwidgets
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/kjobwidgets-5.38.0.tar.xz : a5340df37ba44f6b5b82f8c6732aaaa42ffc6d9a829c15b345e824360eb3e66e
license    : LGPL-2.1
component  : desktop.library
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
