name       : kjobwidgets
version    : 5.109.0
release    : 70
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/kjobwidgets-5.109.0.tar.xz : 860ed5b80d868c42ff957c9d1003d542f9b7fe026c877786dc14969d50a7c2b7
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Widgets for showing progress of asynchronous jobs.
description: |
    Widgets for showing progress of asynchronous jobs.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kcoreaddons-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
